version: '3'
services:
  homeassistant:
    container_name: home-assistant
    restart: unless-stopped
    image: homeassistant/intel-nuc-homeassistant:0.96.5
    # build:
    #   context: .
    #   args:
    #     BUILD_VERSION: 0.96.5
    depends_on:
      - mosquitto
      - mariadb
    ports:
      - "8123:8123"
    volumes:
      - /opt/conf/hass/config:/config
      - /opt/conf/hass/media:/media
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    privileged: true
    logging:
      driver: none

  samba:
    container_name: samba
    image: dperson/samba:latest
    restart: unless-stopped
    environment: 
      - WORKGROUP=workgroup
      - PUID=1001
      - PGID=1001
    ports:
      - "137:137/tcp"
      - "137:137/udp"
      - "138:138/tcp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
      - "445:445/udp"
    volumes:
      - /opt/conf:/mount
    command: 
      -u "roberto;${ROBERTO_PASSWORD}"
      -s "HASS;/mount;yes;no;no;roberto"
    logging:
      driver: none

  nginx:
    image: linuxserver/letsencrypt:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      - EMAIL=${LETSENCRYPT_EMAIL}
      - URL=${HASS_URL}
      - SUBDOMAINS=${HASS_SUBDOMAIN}
      - ONLY_SUBDOMAINS=true
      - VALIDATION=http
      - TZ=Europe/London
    volumes:
      - /opt/conf/nginx/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
      - "443:443"
    cap_add:
      - NET_ADMIN
    logging:
      driver: none

  duckdns:
    image: linuxserver/duckdns:latest
    container_name: duckdns
    restart: unless-stopped
    environment:
      - SUBDOMAINS=${HASS_SUBDOMAIN}
      - TOKEN=${DUCKDNS_TOKEN}
      - TZ=Europe/London
    logging:
      driver: none

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - /opt/conf/mqtt/config:/mosquitto/config
      - /opt/conf/mqtt/data:/mosquitto/data
      - /opt/conf/mqtt/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    expose:
      - "1883"
      - "9001"
    logging:
      driver: none

  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    ports:
      - 9000:9000
    volumes:
      - /opt/conf/portainer/data:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    logging:
      driver: none
  
  watchtower:
    container_name: watchtower
    image: v2tec/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --schedule "0 0 4 * * *"
    logging:
      driver: none

  ble-scanner:
    container_name: ble-scanner
    image: onegambler/mqtt-ble-scanner:latest
    volumes:
      - /opt/conf/mqtt-ble-scanner/config:/mqtt-ble-scanner/config
    restart: unless-stopped
    network_mode: host
    privileged: true
    logging:
      driver: none

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - /opt/conf/mariadb:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_DATABASE=hass
    logging:
      driver: none

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    restart: unless-stopped
    depends_on:
      - mosquitto
    volumes:
      - /opt/conf/zigbee2mqtt:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    logging:
      driver: none
  
  deepstack:
    container_name: deepstack
    image: deepquestai/deepstack:latest
    restart: unless-stopped
    volumes:
      - /opt/conf/deepstack:/datastore
    environment: 
      - VISION-DETECTION=True
    ports:
      - "5000:5000"
    logging:
      driver: none

  linux_dash:
    image: imightbebob/linux-dash:x86
    container_name: linux_dash
    ports:
      - 8080:8080
    restart: unless-stopped
    logging:
      driver: none