version: '2.4'
services:
  home-assistant:
    container_name: home-assistant
    restart: unless-stopped
    image: homeassistant/intel-nuc-homeassistant:2021.5.3
    depends_on:
      mosquitto:
        condition: service_started
      mariadb:
        condition: service_started
      grocy:
        condition: service_started
    ports:
      - "8123:8123"
    environment: 
      - PUID=1001
      - PGID=1001
    volumes:
      - /opt/conf/hass/config:/config
      - /opt/conf/hass/media:/media
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    privileged: true
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8123"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 10
    logging:
      driver: none

  samba:
    container_name: samba
    image: dperson/samba:latest
    restart: unless-stopped
    environment: 
      - WORKGROUP=workgroup
      - PUID=1001
      - PGID=1001
    ports:
      - "137:137/tcp"
      - "137:137/udp"
      - "138:138/tcp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
      - "445:445/udp"
    volumes:
      - /opt/conf:/mount
    command: 
      -u "roberto;${ROBERTO_PASSWORD}"
      -s "HASS;/mount;yes;no;no;roberto;roberto"
    logging:
      driver: none

  swag:
    image: linuxserver/letsencrypt
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - DUCKDNSTOKEN=${DUCKDNS_TOKEN}
      - EMAIL=${LETSENCRYPT_EMAIL}
      - URL=${BASE_URL}
      - ONLY_SUBDOMAINS=false
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - TZ=Europe/Madrid
    volumes:
      - /opt/conf/swag/config:/config
      - /opt/conf/hass/config:/hass
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
    logging:
      driver: none

  # duckdns:
  #   image: linuxserver/duckdns:latest
  #   container_name: duckdns
  #   restart: unless-stopped
  #   environment:
  #     - SUBDOMAINS=${HASS_SUBDOMAIN}
  #     - TOKEN=${DUCKDNS_TOKEN}
  #     - TZ=Europe/Madrid
  #   logging:
  #     driver: none

  mosquitto:
    image: eclipse-mosquitto:1.6.12
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - /opt/conf/mqtt/config:/mosquitto/config
      - /opt/conf/mqtt/data:/mosquitto/data
      - /opt/conf/mqtt/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    expose:
      - "1883"
      - "9001"
    logging:
      driver: none

  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    ports:
      - 9000:9000
    volumes:
      - /opt/conf/portainer/data:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    logging:
      driver: none
  
  watchtower:
    container_name: watchtower
    image: v2tec/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --schedule "0 0 4 * * *"
    logging:
      driver: none

  # ble-scanner:
  #   container_name: ble-scanner
  #   image: onegambler/mqtt-ble-scanner:latest
  #   volumes:
  #     - /opt/conf/mqtt-ble-scanner/config:/mqtt-ble-scanner/config
  #   restart: unless-stopped
  #   network_mode: host
  #   privileged: true
  #   logging:
  #     driver: none

  room-assistant:
    image: mkerix/room-assistant:latest
    restart: unless-stopped
    container_name: room-assistant
    network_mode: host
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /opt/conf/room-assistant/config:/room-assistant/config
    logging:
      driver: none

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - /opt/conf/mariadb:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_DATABASE=hass
    logging:
      driver: none

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    restart: unless-stopped
    depends_on:
      - mosquitto
    volumes:
      - /opt/conf/zigbee2mqtt:/app/data
    ports:
      - "8088:8088"
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    logging:
      driver: none
  
  deepstack:
    container_name: deepstack
    image: deepquestai/deepstack:latest
    restart: unless-stopped
    volumes:
      - /opt/conf/deepstack:/datastore
    environment: 
      - VISION-DETECTION=True
    ports:
      - "5000:5000"
    logging:
      driver: none

  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:4.0.5
    depends_on:
      home-assistant:
        condition: service_started
      grocy:
        condition: service_started
    environment:
      - HA_URL="http://${HOST}:8123"
      - TOKEN=${HASS_APPDAEMON_TOKEN}
      - DASH_URL="http://${HOST}:5050"
    ports:
      - 5050:5050
    volumes:
      # App daemon configuration
      - /opt/conf/hass/config:/conf
      # Timezone configuration (Linux only)
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    logging:
      driver: none

  grocy:
    image: linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /opt/conf/grocy:/config
    ports:
      - 9283:80
    restart: unless-stopped
    logging:
      driver: none

  # selenium:
  #   image: selenium/standalone-chrome
  #   container_name: selenium
  #   ports:
  #     - "4444:4444"
  #   shm_size: '512mb'
  #   restart: unless-stopped
  #   logging:
  #     driver: none